export const PROFILE_NEW_CARDS_PER_DAY_MIN = 10;
export const PROFILE_NEW_CARDS_PER_DAY_MAX = 20;
export const PROFILE_NEW_CARDS_PER_DAY_DEFAULT = 20;

export const clampProfileNewCardsPerDay = (value: number): number => {
	if (!Number.isFinite(value)) {
		return PROFILE_NEW_CARDS_PER_DAY_DEFAULT;
	}

	return Math.min(
		PROFILE_NEW_CARDS_PER_DAY_MAX,
		Math.max(PROFILE_NEW_CARDS_PER_DAY_MIN, Math.round(value)),
	);
};

const PROFILE_COUNTRIES = [
	"Afghanistan",
	"Afrique du Sud",
	"Albanie",
	"Algérie",
	"Allemagne",
	"Andorre",
	"Angola",
	"Antigua-et-Barbuda",
	"Arabie saoudite",
	"Argentine",
	"Arménie",
	"Australie",
	"Autriche",
	"Azerbaïdjan",
	"Bahamas",
	"Bahreïn",
	"Bangladesh",
	"Barbade",
	"Biélorussie",
	"Belgique",
	"Belize",
	"Bénin",
	"Bhoutan",
	"Bolivie",
	"Bosnie-Herzégovine",
	"Botswana",
	"Brésil",
	"Brunei",
	"Bulgarie",
	"Burkina Faso",
	"Burundi",
	"Cambodge",
	"Cameroun",
	"Canada",
	"Cap-Vert",
	"République centrafricaine",
	"Chili",
	"Chine",
	"Chypre",
	"Colombie",
	"Comores",
	"République du Congo",
	"République démocratique du Congo",
	"Corée du Sud",
	"Corée du Nord",
	"Costa Rica",
	"Côte d'Ivoire",
	"Croatie",
	"Cuba",
	"Danemark",
	"Djibouti",
	"République dominicaine",
	"Dominique",
	"Égypte",
	"Émirats arabes unis",
	"Équateur",
	"Érythrée",
	"Espagne",
	"Estonie",
	"États-Unis",
	"Éthiopie",
	"Fidji",
	"Finlande",
	"France",
	"Gabon",
	"Gambie",
	"Géorgie",
	"Ghana",
	"Grèce",
	"Grenade",
	"Guatemala",
	"Guinée",
	"Guinée-Bissau",
	"Guinée équatoriale",
	"Guyana",
	"Haïti",
	"Honduras",
	"Hongrie",
	"Inde",
	"Indonésie",
	"Iran",
	"Irak",
	"Irlande",
	"Islande",
	"Italie",
	"Jamaïque",
	"Japon",
	"Jordanie",
	"Kazakhstan",
	"Kenya",
	"Kirghizistan",
	"Kiribati",
	"Koweït",
	"Laos",
	"Lesotho",
	"Lettonie",
	"Liban",
	"Liberia",
	"Libye",
	"Liechtenstein",
	"Lituanie",
	"Luxembourg",
	"Macédoine du Nord",
	"Madagascar",
	"Malaisie",
	"Malawi",
	"Maldives",
	"Mali",
	"Malte",
	"Maroc",
	"Îles Marshall",
	"Maurice",
	"Mauritanie",
	"Mexique",
	"États fédérés de Micronésie",
	"Moldavie",
	"Monaco",
	"Mongolie",
	"Monténégro",
	"Mozambique",
	"Birmanie",
	"Namibie",
	"Nauru",
	"Népal",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Norvège",
	"Nouvelle-Zélande",
	"Oman",
	"Ouganda",
	"Ouzbékistan",
	"Pakistan",
	"Palestine",
	"Palaos",
	"Panama",
	"Papouasie-Nouvelle-Guinée",
	"Paraguay",
	"Pays-Bas",
	"Pérou",
	"Philippines",
	"Pologne",
	"Portugal",
	"Qatar",
	"Roumanie",
	"Royaume-Uni",
	"Russie",
	"Rwanda",
	"Saint-Christophe-et-Niévès",
	"Saint-Marin",
	"Saint-Vincent-et-les-Grenadines",
	"Sainte-Lucie",
	"Îles Salomon",
	"Salvador",
	"Samoa",
	"Sao Tomé-et-Principe",
	"Sénégal",
	"Serbie",
	"Seychelles",
	"Sierra Leone",
	"Singapour",
	"Slovaquie",
	"Slovénie",
	"Somalie",
	"Soudan",
	"Soudan du Sud",
	"Sri Lanka",
	"Suède",
	"Suisse",
	"Suriname",
	"Eswatini",
	"Syrie",
	"Tadjikistan",
	"Tanzanie",
	"Tchad",
	"Tchéquie",
	"Thaïlande",
	"Timor oriental",
	"Togo",
	"Tonga",
	"Trinité-et-Tobago",
	"Tunisie",
	"Turkménistan",
	"Turquie",
	"Tuvalu",
	"Ukraine",
	"Uruguay",
	"Vanuatu",
	"Venezuela",
	"Vietnam",
	"Yémen",
	"Zambie",
	"Zimbabwe",
] as const;

export const PROFILE_COUNTRY_OPTIONS = PROFILE_COUNTRIES.map((country) => ({
	label: country,
	value: country,
}));

const PROFILE_COUNTRY_SET = new Set<string>(PROFILE_COUNTRIES);

export const isSupportedProfileCountry = (
	value: string | null | undefined,
): boolean => {
	const normalizedValue = typeof value === "string" ? value.trim() : "";
	return PROFILE_COUNTRY_SET.has(normalizedValue);
};
