export const PROFILE_NEW_CARDS_PER_DAY_MIN = 10;
export const PROFILE_NEW_CARDS_PER_DAY_MAX = 20;
export const PROFILE_NEW_CARDS_PER_DAY_DEFAULT = 20;

export const clampProfileNewCardsPerDay = (value: number): number => {
	if (!Number.isFinite(value)) {
		return PROFILE_NEW_CARDS_PER_DAY_DEFAULT;
	}

	return Math.min(
		PROFILE_NEW_CARDS_PER_DAY_MAX,
		Math.max(PROFILE_NEW_CARDS_PER_DAY_MIN, Math.round(value)),
	);
};

const PROFILE_COUNTRIES = [
	"Afghanistan",
	"South Africa",
	"Albania",
	"Algeria",
	"Germany",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Saudi Arabia",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cape Verde",
	"Central African Republic",
	"Chile",
	"China",
	"Cyprus",
	"Colombia",
	"Comoros",
	"Republic of the Congo",
	"Democratic Republic of the Congo",
	"South Korea",
	"North Korea",
	"Costa Rica",
	"Ivory Coast",
	"Croatia",
	"Cuba",
	"Denmark",
	"Djibouti",
	"Dominican Republic",
	"Dominica",
	"Egypt",
	"United Arab Emirates",
	"Ecuador",
	"Eritrea",
	"Spain",
	"Estonia",
	"United States",
	"Ethiopia",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia",
	"Georgia",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea-Bissau",
	"Equatorial Guinea",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hungary",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Iceland",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kyrgyzstan",
	"Kiribati",
	"Kuwait",
	"Laos",
	"Lesotho",
	"Latvia",
	"Lebanon",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"North Macedonia",
	"Madagascar",
	"Malaysia",
	"Malawi",
	"Maldives",
	"Mali",
	"Malta",
	"Morocco",
	"Marshall Islands",
	"Mauritius",
	"Mauritania",
	"Mexico",
	"Federated States of Micronesia",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Norway",
	"New Zealand",
	"Oman",
	"Uganda",
	"Uzbekistan",
	"Pakistan",
	"Palestine",
	"Palau",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Netherlands",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Romania",
	"United Kingdom",
	"Russia",
	"Rwanda",
	"Saint Kitts and Nevis",
	"San Marino",
	"Saint Vincent and the Grenadines",
	"Saint Lucia",
	"Solomon Islands",
	"El Salvador",
	"Samoa",
	"Sao Tome and Principe",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Somalia",
	"Sudan",
	"South Sudan",
	"Sri Lanka",
	"Sweden",
	"Switzerland",
	"Suriname",
	"Eswatini",
	"Syria",
	"Tajikistan",
	"Tanzania",
	"Chad",
	"Czech Republic",
	"Thailand",
	"East Timor",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkmenistan",
	"Turkey",
	"Tuvalu",
	"Ukraine",
	"Uruguay",
	"Vanuatu",
	"Venezuela",
	"Vietnam",
	"Yemen",
	"Zambia",
	"Zimbabwe",
] as const;

export const PROFILE_COUNTRY_OPTIONS = [...PROFILE_COUNTRIES]
	.sort((left, right) => left.localeCompare(right, "en"))
	.map((country) => ({
	label: country,
	value: country,
	}));

const PROFILE_COUNTRY_SET = new Set<string>(PROFILE_COUNTRIES);

export const isSupportedProfileCountry = (
	value: string | null | undefined,
): boolean => {
	const normalizedValue = typeof value === "string" ? value.trim() : "";
	return PROFILE_COUNTRY_SET.has(normalizedValue);
};
