// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import { supabaseAuthStorage } from "@/lib/authPersistence";
import type { Database } from "./types";

type RuntimeSupabaseConfig = {
	SUPABASE_URL?: string;
	SUPABASE_PUBLISHABLE_KEY?: string;
	DECK_PERSO_REAL_MODE_ENABLED?: boolean;
	PROGRESSION_REAL_MODE_ENABLED?: boolean;
	DECK_PERSO_FORCE_MODE?: "preview" | "real" | null;
	PROGRESSION_FORCE_MODE?: "preview" | "real" | null;
	DECK_PERSO_ROLLBACK_TO_PREVIEW?: boolean;
	PROGRESSION_ROLLBACK_TO_PREVIEW?: boolean;
	APPRENDRE_CUES_MASTER_STORAGE_ENABLED?: boolean;
	APPRENDRE_ASS_SPIKE_ENABLED?: boolean;
	APPRENDRE_ASS_SPIKE_VIDEO_ID?: string | null;
};

type WindowWithSupabaseConfig = Window & {
	__SUPABASE_CONFIG__?: RuntimeSupabaseConfig;
};

type ViteEnvLike = Record<string, string | boolean | undefined>;

const normalizeOptionalString = (value: unknown): string | undefined => {
	if (typeof value !== "string") {
		return undefined;
	}

	const trimmedValue = value.trim();
	return trimmedValue.length > 0 ? trimmedValue : undefined;
};

const normalizeSupabaseUrl = (value: unknown): string | undefined => {
	const normalizedValue = normalizeOptionalString(value);
	if (!normalizedValue) {
		return undefined;
	}

	try {
		const parsedUrl = new URL(normalizedValue);
		if (parsedUrl.protocol !== "http:" && parsedUrl.protocol !== "https:") {
			return undefined;
		}

		return normalizedValue;
	} catch {
		return undefined;
	}
};

const decodeBase64UrlSegment = (segment: string): string | null => {
	if (typeof globalThis.atob !== "function") {
		return null;
	}

	const normalizedSegment = segment.replace(/-/g, "+").replace(/_/g, "/");
	const paddingLength = (4 - (normalizedSegment.length % 4)) % 4;
	const padding = "=".repeat(paddingLength);

	try {
		return globalThis.atob(`${normalizedSegment}${padding}`);
	} catch {
		return null;
	}
};

const isServiceRoleJwt = (value: string): boolean => {
	const segments = value.split(".");
	if (segments.length !== 3) {
		return false;
	}

	const payload = decodeBase64UrlSegment(segments[1]);
	if (!payload) {
		return false;
	}

	try {
		const parsedPayload = JSON.parse(payload) as { role?: unknown };
		return parsedPayload.role === "service_role";
	} catch {
		return false;
	}
};

const isUnsafeBrowserSupabaseKey = (value: string): boolean =>
	value.startsWith("sb_secret_") || isServiceRoleJwt(value);

const normalizeSupabasePublishableKey = (value: unknown): string | undefined => {
	const normalizedValue = normalizeOptionalString(value);
	if (!normalizedValue) {
		return undefined;
	}

	if (isUnsafeBrowserSupabaseKey(normalizedValue)) {
		return undefined;
	}

	return normalizedValue;
};

const viteEnv: ViteEnvLike =
	(import.meta as ImportMeta & { env?: ViteEnvLike }).env ?? {};

const runtimeConfig =
	typeof window === "undefined"
		? undefined
		: (window as WindowWithSupabaseConfig).__SUPABASE_CONFIG__;

const ENV_SUPABASE_URL = normalizeSupabaseUrl(
	viteEnv.VITE_SUPABASE_URL ?? viteEnv.SUPABASE_URL,
);

const RAW_ENV_SUPABASE_PUBLISHABLE_KEY = normalizeOptionalString(
	viteEnv.VITE_SUPABASE_PUBLISHABLE_KEY ?? viteEnv.SUPABASE_KEY,
);
const ENV_SUPABASE_PUBLISHABLE_KEY = normalizeSupabasePublishableKey(
	RAW_ENV_SUPABASE_PUBLISHABLE_KEY,
);

const SUPABASE_URL = normalizeSupabaseUrl(
	runtimeConfig?.SUPABASE_URL ?? ENV_SUPABASE_URL,
);
const RAW_RUNTIME_SUPABASE_PUBLISHABLE_KEY = normalizeOptionalString(
	runtimeConfig?.SUPABASE_PUBLISHABLE_KEY,
);
const RUNTIME_SUPABASE_PUBLISHABLE_KEY = normalizeSupabasePublishableKey(
	RAW_RUNTIME_SUPABASE_PUBLISHABLE_KEY,
);
const SUPABASE_PUBLISHABLE_KEY =
	RUNTIME_SUPABASE_PUBLISHABLE_KEY ?? ENV_SUPABASE_PUBLISHABLE_KEY;

const hasBlockedRuntimeSupabaseKey = Boolean(
	RAW_RUNTIME_SUPABASE_PUBLISHABLE_KEY && !RUNTIME_SUPABASE_PUBLISHABLE_KEY,
);
const hasBlockedEnvSupabaseKey = Boolean(
	!RAW_RUNTIME_SUPABASE_PUBLISHABLE_KEY &&
		RAW_ENV_SUPABASE_PUBLISHABLE_KEY &&
		!ENV_SUPABASE_PUBLISHABLE_KEY,
);

const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
const missingSupabaseConfigMessage =
	"Supabase config missing. Set runtime-config.json or env vars (VITE_SUPABASE_URL + VITE_SUPABASE_PUBLISHABLE_KEY, or SUPABASE_URL + SUPABASE_KEY).";
const blockedSupabaseServiceKeyMessage =
	"Refusing to use a Supabase service-role key in browser config. Set a publishable key instead.";

const missingConfigFetch: typeof fetch | undefined = hasSupabaseConfig
	? undefined
	: async () => {
			throw new Error(missingSupabaseConfigMessage);
		};

if (!hasSupabaseConfig) {
	console.warn(missingSupabaseConfigMessage);
}

if (hasBlockedRuntimeSupabaseKey || hasBlockedEnvSupabaseKey) {
	console.error(blockedSupabaseServiceKeyMessage);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
	SUPABASE_URL ?? "https://placeholder.supabase.co",
	SUPABASE_PUBLISHABLE_KEY ?? "sb_publishable_placeholder",
	{
		auth: {
			storage: supabaseAuthStorage,
			persistSession: true,
			autoRefreshToken: true,
		},
		global: missingConfigFetch ? { fetch: missingConfigFetch } : undefined,
	},
);
