// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import { supabaseAuthStorage } from "@/lib/authPersistence";
import type { Database } from "./types";

type RuntimeSupabaseConfig = {
	SUPABASE_URL?: string;
	SUPABASE_PUBLISHABLE_KEY?: string;
	DECK_PERSO_REAL_MODE_ENABLED?: boolean;
	PROGRESSION_REAL_MODE_ENABLED?: boolean;
	DECK_PERSO_FORCE_MODE?: "preview" | "real" | null;
	PROGRESSION_FORCE_MODE?: "preview" | "real" | null;
	DECK_PERSO_ROLLBACK_TO_PREVIEW?: boolean;
	PROGRESSION_ROLLBACK_TO_PREVIEW?: boolean;
	APPRENDRE_CUES_MASTER_STORAGE_ENABLED?: boolean;
	APPRENDRE_ASS_SPIKE_ENABLED?: boolean;
	APPRENDRE_ASS_SPIKE_VIDEO_ID?: string | null;
};

type WindowWithSupabaseConfig = Window & {
	__SUPABASE_CONFIG__?: RuntimeSupabaseConfig;
};

type ViteEnvLike = Record<string, string | boolean | undefined>;

const normalizeOptionalString = (value: unknown): string | undefined => {
	if (typeof value !== "string") {
		return undefined;
	}

	const trimmedValue = value.trim();
	return trimmedValue.length > 0 ? trimmedValue : undefined;
};

const normalizeSupabaseUrl = (value: unknown): string | undefined => {
	const normalizedValue = normalizeOptionalString(value);
	if (!normalizedValue) {
		return undefined;
	}

	try {
		const parsedUrl = new URL(normalizedValue);
		if (parsedUrl.protocol !== "http:" && parsedUrl.protocol !== "https:") {
			return undefined;
		}

		return normalizedValue;
	} catch {
		return undefined;
	}
};

const viteEnv: ViteEnvLike =
	(import.meta as ImportMeta & { env?: ViteEnvLike }).env ?? {};

const runtimeConfig =
	typeof window === "undefined"
		? undefined
		: (window as WindowWithSupabaseConfig).__SUPABASE_CONFIG__;

const ENV_SUPABASE_URL = normalizeSupabaseUrl(
	viteEnv.VITE_SUPABASE_URL ?? viteEnv.SUPABASE_URL,
);

const ENV_SUPABASE_PUBLISHABLE_KEY = normalizeOptionalString(
	viteEnv.VITE_SUPABASE_PUBLISHABLE_KEY ?? viteEnv.SUPABASE_KEY,
);

const SUPABASE_URL = normalizeSupabaseUrl(
	runtimeConfig?.SUPABASE_URL ?? ENV_SUPABASE_URL,
);
const SUPABASE_PUBLISHABLE_KEY = normalizeOptionalString(
	runtimeConfig?.SUPABASE_PUBLISHABLE_KEY ?? ENV_SUPABASE_PUBLISHABLE_KEY,
);

const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
const missingSupabaseConfigMessage =
	"Supabase config missing. Set runtime-config.json or env vars (VITE_SUPABASE_URL + VITE_SUPABASE_PUBLISHABLE_KEY, or SUPABASE_URL + SUPABASE_KEY).";

const missingConfigFetch: typeof fetch | undefined = hasSupabaseConfig
	? undefined
	: async () => {
			throw new Error(missingSupabaseConfigMessage);
		};

if (!hasSupabaseConfig) {
	console.warn(missingSupabaseConfigMessage);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
	SUPABASE_URL ?? "https://placeholder.supabase.co",
	SUPABASE_PUBLISHABLE_KEY ?? "sb_publishable_placeholder",
	{
		auth: {
			storage: supabaseAuthStorage,
			persistSession: true,
			autoRefreshToken: true,
		},
		global: missingConfigFetch ? { fetch: missingConfigFetch } : undefined,
	},
);
